FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies and cache the result.
COPY package.json .
COPY yarn.lock .
RUN [ "yarn", "install" ]

# Copy other top level files.
# Add a line for every file used for builds.
COPY .eslintrc .
COPY tsconfig.json .
COPY postcss.config.js .
COPY tailwind.config.js .

EXPOSE 3000
ENTRYPOINT [ "yarn", "dev" ]